### PR TITLE
somayeh mohamadiyan

### PR DESCRIPTION
**Pull request by somayehmohamadyan**
https://github.com/debug-ashena/Slides/blob/NetworkOS/PracticeGit

### CODE REVIEW

**Comment by somayehmohamadyan** [comment]
somayeh mohamadiyan term2

**Comment by somayehmohamadyan** [comment]
somayeh mohamadiyan

**Comment by amirhossein320** [comment]
یسبسیبسیب

**Review by debug-ashena — APPROVED** [review]
Somayeh Mohammadian got her point,

**Review by debug-ashena — APPROVED** [review]

**Pull request merged**
